### ISSUE TITLE
Pipe naming automation/support

### ISSUE THREAD

**Issue by zuckerruebe** [SPF-OST/pytrnsys_gui#129] opened 2021-09-28 12:13 UTC
See https://github.com/SPF-OST/pytrnsys_gui/wiki/Naming-pipes.

**Comment by martin-neugebauer** [comment] 2021-11-23 14:08
Could be integrated into #191

**Comment by martin-neugebauer** [comment] 2022-03-04 12:56
Duplicate of #233

**Closed by martin-neugebauer** 2022-03-04 12:56 UTC
Labels: epic, ddck-generation-all-items
